### ISSUE TITLE
Unable to view pinned messages.

### ISSUE THREAD

**Issue by BennyDoesStuff** [forumsgg/Issues#11]
### Expected behavior
When you make it so people can post in a category but not view other posts in it, the only post they should be able to view is any pinned messages such as a format.

### Actual behavior
The person is unable to view the pinned message when they click the category.

### Detailed steps to reproduce this behavior
Make a category that people can post in but not view. 

### Link to site
https://forums.minehut.com

**Comment by lukechatton** [comment]
Which category on Minehut is having this issue? Could you send a link.

**Comment by lukechatton** [comment]
I pushed a fix for users not being able to see anything while they are signed out. But I'm not sure if that's the bug you were referring to.

**Comment by BennyDoesStuff** [comment]
Yea seems like that push fixed it.
