### ISSUE TITLE
Can't view own post on topics with viewing limited.

### ISSUE THREAD

**Issue by BennyDoesStuff** [forumsgg/Issues#15]
### Expected behavior
If you allow someone to post on a topic but can't view it, they shouldn't be allowed to view other post but still be able to view their own post if they post something.

### Actual behavior
After you post something, it will still be viewable by anyone with the permission to view it, but you are unable to view your own post.

### Detailed steps to reproduce this behavior
Make a topic with viewing limited to certain people but allow posting for everything. If you post something but you do not have perms to view it, you're not able to view your own post.

### Link to site
https://forums.minehut.com (Applications section).

**Comment by lukechatton** [comment]
Should be fixed. Re-open if issue persists 🙂
