### ISSUE TITLE
Add Custom Pages only certain roles can see

### ISSUE THREAD

**Issue by BennyDoesStuff** [forumsgg/Issues#6]
The ability to add custom pages but limit who can actually view the page to certain roles. This would be nice if you are going to add guidelines or private links that you only want staff members or donators to see. If you don't have access to that custom page/don't have the role, it should instead redirect you to the main forums page (name.forums.gg etc).

**Comment by Sniped** [comment]
Couldn't you just have a private category for that? It seems useless to add restricted pages when you can just customize categories and put posts there.
